pattern:
  - .{5,}
  - (.)\1\1
  - ([A-Z]|.*\W)
  - ^(?=.*[0-9])
match:
  - false
  - true
  - false
  - false
message:
  - minimum 5 character
  - three or more repeating consecutive characters  
  - you have to use at least one upper-case character or one special character 
  - minimum 1 number