pattern:
  - .{5,}
  - (.)\1\1
  - ([A-Z]|.*\W)
  - ^(?=.*[0-9])
match:
  - false
  - true
  - false
  - false
message:
  - The password contains minimum 5 characters.
  - The password cannot contain three or more repeating consecutive characters.
  - You have to use at least one upper-case character or one special character.
  - The password contains minimum 1 number.